simulations:
  simulation1:
    rounds: 3                   # Number of training rounds
    epochs: 1                   # Number of epochs per round
    num_nodes: 5                # Total number of nodes in the simulation
    num_attackers: 0            # Number of attacker nodes
    attacker_nodes: []          # Specific nodes designated as attackers
    attacks: [poison]           # Types of attacks to simulate
    use_attackers: false        # Flag to enable or disable attacker simulation
    participation_rate: 0.6     # Fraction of nodes participating each round
    topology: fully_connected   # Network topology type
    topology_file: null         # Path to a custom topology edge list file
    max_attacks: null           # Maximum number of attacks an attacker can perform
    gossip_steps: 3             # Number of gossiping steps during aggregation
    protocol: gossip            # Aggregation protocol ('gossip' or 'neighboring')
    alpha: 0.5                  # Dirichlet distribution parameter for data partitioning
    model_type: cnn             # Model type to use ('cnn', 'mlp', or custom)
