simulations:
  simulation1:
    rounds: 10                  # Number of training rounds
    epochs: 10                  # Number of epochs per round
    num_nodes: 3                # Total number of nodes in the simulation
    node_type_map: 
      0: 'base'
      1: 'base'
      2: 'poison'
    use_attackers: true         # Flag to enable or disable attacker simulation 
    participation_rate: 0.6     # Fraction of nodes participating each round ## DELETE
    topology: fully_connected   # Network topology type
    topology_file: null         # Path to a custom topology edge list file
    max_attacks: 5              # Maximum number of attacks an attacker can perform
    gossip_steps: 3             # Number of gossiping steps during aggregation
    protocol: neighboring       # Aggregation protocol ('gossip' or 'neighboring')
    alpha: 0.5                  # Dirichlet distribution parameter for data partitioning ### LOOK INTO WHAT THIS IS
    model_type: cnn             # Model type to use ('cnn', 'mlp', or custom)