nodes:
  0:
    dataset: ./results_58/federated_data/node_0_train_data.pt
    epochs: 1
    model: cnn
    neighbors:
    - 1
    rounds: 3
    type: base
  1:
    dataset: ./results_58/federated_data/node_1_train_data.pt
    epochs: 1
    model: cnn
    neighbors:
    - 0
    rounds: 3
    type: base
